spring:
  config:
    activate:
      on-profile: prod
  # MariaDB 데이터베이스 설정
  datasource:
    url: jdbc:mariadb://${DB_HOST}:3306/diary?allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&useSSL=false
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.mariadb.jdbc.Driver
