aws:
  s3:
    bucket: picdiarystudy
  credentials:
    access-key: AKIARUDZFJZUKV7BPD4J
    secret-key: ${S3_ACCESS_SECRET}
  region:
    static: ap-northeast-2
    auto: false
  stack:
    auto: false

spring:
  datasource:
    tomcat:
      max-active: 5
  profiles:
    active: local
  # Flyway 설정
  flyway:
    locations: classpath:db.migration
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

swagger:
  url: http://localhost:8080

# 로깅 설정
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
