spring:
  profiles:
    active: local
  # Flyway 설정
  flyway:
    locations: classpath:db.migration
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

# 로깅 설정
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
