spring:
  config:
    activate:
      on-profile: dev
  # MariaDB 데이터베이스 설정
  datasource:
    url: jdbc:mariadb://${DB_HOST}:3306/diary-test?allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&useSSL=false
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      initializationFailTimeout: 9000
      maximum-pool-size: 3
      minimum-idle: 1
