ALTER TABLE diary
ADD COLUMN emotion ENUM('HAPPY', 'SAD', 'ANGRY', 'EXCITED', 'CALM', 'CONFUSED', 'LOVE', 'SURPRISED', 'EXERCISE'),
ADD CONSTRAINT `unique_diary_user_date` UNIQUE (`user_id`, `date`);

ALTER TABLE todo
ALTER COLUMN id BIGINT PRIMARY KEY AUTO_INCREMENT,
DROP COLUMN date DATETIME NOT NULL;
