name: Spring Boot Test

on:
  pull_request:
    branches: master
  push:
    branches: master
    tags: [v*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Save secrets as .env file
        run: |
            echo $SECRETS_CONTEXT | jq -r 'to_entries[] | "\(.key)=\(.value)\n"' > src/main/resources/.env
        env:
          SECRETS_CONTEXT: ${{toJSON(secrets)}}

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Run Gradle Test
        run: ./gradlew test
